### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by AramPetiet** [richelbilderbeek/internship_aram#1]
Hey! So this is me. I don't know what to put here because i don't know what has been said about me already. 
Short introduction just in case,
I'm Aram,
15 years old,
Year 3 on the Montessori Vaklyceum,
I love computers and helping others,
I can work alone pretty well.

Any questions about me or anything, just ask

**Comment by richelbilderbeek** [comment]
Cool, I added you to the Collaborator list. Make sure to accept the invite from GitHub :+1:
